shamefullyHoist: true

# lock package for 3 days to prevent supply chain
minimumReleaseAge: 4320

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  # Renovate security update: @nuxt/devtools@3.3.1
  - "@nuxt/devtools@3.3.1"
